name: CI

on:
  push:
    branches: ["**"]
    tags-ignore: ["v*"]
  pull_request:

jobs:
  ci:
    name: Fmt + Test + Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Permissão do script
        run: chmod +x scripts/build.sh
      - name: CI
        run: ./scripts/build.sh
